version: "3.6"
services:
  minetest:
    image: minetest_irc
    volumes:
      - minetest_data:/config/.minetest
    ports:
      - 30000:30000/udp
    environment:
      - PUID=1000
      - PGID=1000
        - CLI_ARGS=--gameid minetest
    depends_on:
      - irc
  irc:
    image: linuxserver/ngircd
    ports:
      - 6667:6667
      - 6697:6697
    environment:
      - PUID=1000
      - PGID=1000

volumes:
  minetest_data: {}

